apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-script-cronjob
spec:
  schedule: "*/5 * * * *"  # Ejecuta cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-script
              image: jaimeheano8126/deploy-script:latest  # Cambia esto
              env:
                - name: SLACK_WEBHOOK_URL
                  value: "https://hooks.slack.com/services/..."  # Reemplaza con tu URL de webhook de Slack
          restartPolicy: OnFailure